matrix:
  include:
    - language: node_js
      node_js: '12'
      python: '3.7'
      dist: bionic
      addons: 
        sonarcloud:
          organization: "swsnu"
          token: 
            secure: "n1TpWdEA3g432hAnfba7a7OK85zX5dhOpAJyCWVF9wBvAYBZZssF9GEK7DwrKXe+UnbXg+SmBLKq6r0PF3fj+/OTXMlBm1zphw7fYtjT3ihTwnD4EWZhA54QCl1t5Qbeh11shRJHsLTnsFq3mIDoY1TFnqSNjm5NmwM1O/WOiBlBPOx3uZo9ulAqsQIJnzCNDLrXCsRMrERKIIIuPV19YlD1xNVT1hCU+mhoA3wVmSVNrdCZgqPDqK3JUUR4ojycTISKF6xo00xAwyBo5UhxupDoOlMygi3Er4bfuleEOFhSyx/+mcGyynfdb6xieS17zANcYsNgB72S8Rojjb44d3ISRGiIWnaLAJjkb18VsR8kAzLMxJ6XJTGDnJTIaXdsoqD+K3XJcSSOB6IuDGVYBQHz2s9Mauzt6EKWhkZy/6rii2Z+Xxwowxd74Gw73TaVpMs9WzhLRDNrlZI+SzB0DZe1oatPt4W/j1PB7yqQhXanuRV7W0YuxE7VM42WmsLHkVjfFB4351xtniBpOb0F9TwhB/2pkUYvml9ZBKg/O7lFuPQS5qdm0FAN/9egfcre6FdtzlepKl3RpVFV9uvfWEK3AWuoIvStTBFOqeySDnPPYHgsA2Cf5BXNyufRYr6+8bnghmaiU/FvpOogfdSoqa1zlL7lnK+ioRGBgv8IPE4="
      cache:
        - yarn: true
        - pip: true
      before_install:
        - cd frontend
      install:
        - yarn install
        - yarn add coveralls
        - cd ..
        - cd backend
        - source ~/virtualenv/python3.7/bin/activate
        - pip install -r requirements.txt
        - python -m pip install Pillow
        - gem install coveralls-lcov
      script:
        - cd ..
        - cd frontend
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
        - coveralls-lcov -v -n coverage/lcov.info > coverage/coverage.json
        - cd ..
        - cd backend
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test recipick
        - coverage xml
        - cd ..
        - sonar-scanner
      after_success:
        - cd backend
        - coveralls --merge=../frontend/coverage/coverage.json
