# Generated by Django 3.1.1 on 2020-11-16 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0002_auto_20201110_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='photo_list',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_list', to='recipick.recipe'),
        ),
    ]
